<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMerchantsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('merchants', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name')->comment('Merchant Full name to identify');
            $table->string('slug')->unique()->comment('Merchant short identifier generated by system');
            $table->text('endpoint')->comment('Where system will send notification')->nullable();
            $table->string('contact')->nullable();
            $table->string('account_no')->unique();
            $table->string('status')->index()->comment('ACTIVE or INACTIVE');
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('merchants');
    }
}
